# Stage 1: Build React
FROM node:20-alpine AS builder

WORKDIR /app

# 빌드 스크립트를 build arg로 전달
ARG BUILD_SCRIPT=build:localserver

COPY ./client ./
RUN npm install
RUN npm run $BUILD_SCRIPT

# Stage 2: Nginx + React
FROM nginx:stable-alpine

COPY --from=builder /app/build /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
