# Stage 1: Build React
FROM node:20-alpine AS builder

WORKDIR /app

# 빌드 스크립트를 build arg로 전달
ARG BUILD_SCRIPT=build:localserver

COPY ./client/package*.json ./
RUN npm install

COPY ./client .
COPY ./client/.env.production ./.env.production
RUN npm run $BUILD_SCRIPT

# Stage 2: Nginx + React
FROM nginx:stable-alpine

COPY --from=builder /app/build /usr/share/nginx/html
COPY ./nginx/default.ec2.conf /etc/nginx/conf.d/default.conf
