# Stage 1: Build React
FROM node:20-alpine AS builder

WORKDIR /app
COPY ./client .
RUN npm install && npm run build:localserver

# Stage 2: Nginx + React
FROM nginx:stable-alpine

# React 빌드 결과 복사
COPY --from=builder /app/build /usr/share/nginx/html

# Nginx 설정 복사
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf