services:
  nginx:
    build:
      context: .
      dockerfile: client/Dockerfile.nginx-react
    container_name: nginx-react
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server

  server:
    build: ./server
    container_name: nest_api
    restart: always
    expose:
      - "4000"
    env_file:
      - ./server/.env.local
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - ./server/.env.local
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
