version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - ./env/db.env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: piled-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./env/app.docker.env

volumes:
  db-data:
