server {
    listen 80;
    server_name piled-time.com www.piled-time.com;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location ~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl;
    server_name piled-time.com www.piled-time.com;

    ssl_certificate /etc/letsencrypt/live/piled-time.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/piled-time.com/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
