name: Build and Push Docker Images

on:
  push:
    branches: [main]

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ .env 파일 생성 (서버용 환경 변수)
      - name: Create .env file for docker-compose
        run: |
          mkdir -p server
          echo "DB_HOST=db" >> server/.env.local
          echo "DB_USER=${{ secrets.DB_USER }}" >> server/.env.local
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> server/.env.local
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.DB_PASS }}" >> server/.env.local

      # ✅ Docker Hub 로그인
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      # ✅ Build & Push React
      - name: Build and Push React image (dist only)
        run: |
          docker build -t $DOCKER_USER/react_app ./client
          docker push $DOCKER_USER/react_app

      # ✅ Build & Push NestJS
      - name: Build and Push NestJS image
        run: |
          docker build --env-file ./server/.env.local -t $DOCKER_USER/nest_api ./server
          docker push $DOCKER_USER/nest_api
